<template>
    <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <!-- <div v-if="successMessage" class="alert alert-success">{{successMessage}}</div> -->
                    <div class="card card-header">NEW Note</div>
                    <div class="card-body">
                            <!-- //submit.prevent == onclick.prevent d+i js  -->
                        <form action="#" method="POST" @submit.prevent="store">
                            <div class="form-group">
                                <label for="Input-title" >Title</label>
                                <input type="text" v-model="form.title" id="Input-title" class="form-control">
                                <div v-if="theErrors.title" class="mt-2 text-danger">{{ theErrors.title[0]}}</div>
                            </div>
                            <div class="form-group">
                                <label for="Input-subject" >Subject</label>
                                <select type="text" v-model="form.subject" id="Input-subject" class="form-control">
                                    <option v-for="subject in subjects" :key="subject.id" :value="subject.id">{{ subject.name }}</option>
                                </select>
                                <div v-if="theErrors.subject" class="mt-2 text-danger">{{ theErrors.subject[0]}}</div>
                            </div>
                            <div class="form-group">
                                <label for="Input-describtion" >Describtion</label>
                                <textarea v-model="form.description" id="Input-describtion" cols="30" rows="10" class="form-control"></textarea>
                                <div v-if="theErrors.description" class="mt-2 text-danger">{{ theErrors.description[0]}}</div>
                            </div>

                            <button type="submit" class="btn btn-primary d-flex align-items-center"> Simpan

                                 <template v-if="loading">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="20px" height="20px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                                <g>
                                <circle cx="60" cy="50" r="4" fill="#e76a24">
                                    <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="-0.67s"></animate>
                                    <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="-0.67s"></animate>
                                </circle>
                                <circle cx="60" cy="50" r="4" fill="#e76a24">
                                    <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="-0.33s"></animate>
                                    <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="-0.33s"></animate>
                                </circle>
                                <circle cx="60" cy="50" r="4" fill="#e76a24">
                                    <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="0s"></animate>
                                    <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="0s"></animate>
                                </circle>
                                </g><g transform="translate(-15 0)">
                                <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#1c4595" transform="rotate(90 50 50)"></path>
                                <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#1c4595">
                                    <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;45 50 50;0 50 50" keyTimes="0;0.5;1"></animateTransform>
                                </path>
                                <path d="M50 50L20 50A30 30 0 0 1 80 50Z" fill="#1c4595">
                                    <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;-45 50 50;0 50 50" keyTimes="0;0.5;1"></animateTransform>
                                </path>
                                </g>
                                <!-- [ldio] generated by https://loading.io/ --></svg>
                                 </template>
                            </button>




                        </form>

                    </div>
                </div>
            </div>
    </div>
</template>

<script>
export default {
    data(){
        return{
            //form data yang akan dikirim
            form:{
                title:'',
                description:'',
                subjects:'',
            },
            // successMessage:'',
            loading:false,
            subjects:[],
            theErrors:[]
        };
    },
    mounted(){
        this.getsubjects();
    },
    methods:{
        async getsubjects(){
            let response = await axios.get('/api/subjects')
            // console.log(response.data);
            if(response.status === 200){
                this.subjects=response.data
            }
        },
        async store(){
            this.loading=true;
        try{
            let response = await axios.post('/api/notes/create-new-note', this.form)
            if(response.status==200){
                // console.log(response.data);
                this.form.title=""
                this.form.description=""
                this.form.subject=""
                this.loading=false
                this.theErrors=[]
                // this.successMessage=response.data.message
                // this.$toasted.show(response.data.message)
                let toast = this.$toasted.show(response.data.message, {
                    type:'success',
                    theme: "bubble",
                    position: "top-right",
                    duration : 5000
                });
            }
            // console.log(response.data.message);
        }catch(e){
                this.loading=false
            this.theErrors=e.response.data.errors;
               let toast = this.$toasted.show("Terjadi kesalahan!", {
                    type:'error',
                    theme: "bubble",
                    position: "top-right",
                    duration : 5000
                });
        }
        }
    }


}
</script>

<style>

</style>
