<template>
    <div class="container">
            <div class="row">
                <div class="col-md-6 container-fluid">
                    <!-- <div v-if="successMessage" class="alert alert-success">{{successMessage}}</div> -->
                    <h2 class="text-center mb-3">TAMBAH DATA</h2>
                    <hr>

                            <!-- //submit.prevent == onclick.prevent d+i js  -->
                        <form action="#" method="POST" @submit.prevent="store">
                            <div class="form-group">
                                <label for="Input-nama" >NAMA</label>
                                <input type="text" v-model="form.nama" id="Input-nama" class="form-control">
                                <div v-if="theErrors.nama" class="mt-2 text-danger">{{ theErrors.nama[0]}}</div>
                            </div>
                            <div class="form-group">
                                <label for="Input-bobot" >Bobot</label>
                                <input type="number" v-model="form.bobot" id="Input-bobot" class="form-control">
                                <div v-if="theErrors.bobot" class="mt-2 text-danger">{{ theErrors.bobot[0]}}</div>
                            </div>
                            <div class="form-group">
                                <!-- <label for="Input-kriteria_id" >Kriteria id</label> -->
                                <input type="hidden" v-model="form.kriteria_id" id="Input-kriteria_id" class="form-control">
                                <div v-if="theErrors.kriteria_id" class="mt-2 text-danger">{{ theErrors.kriteria_id[0]}}</div>
                            </div>

                        <div class="row">

                         <div class="col-lg-12 d-flex flex-row-reverse">
                            <button type="submit" class="btn btn-outline-primary d-flex align-items-center mt-2"> Simpan

                                 <template v-if="loading">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: none; display: block; shape-rendering: auto;" width="20px" height="20px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                                <g>
                                <circle cx="60" cy="50" r="4" fill="#e76a24">
                                    <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="-0.67s"></animate>
                                    <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="-0.67s"></animate>
                                </circle>
                                <circle cx="60" cy="50" r="4" fill="#e76a24">
                                    <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="-0.33s"></animate>
                                    <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="-0.33s"></animate>
                                </circle>
                                <circle cx="60" cy="50" r="4" fill="#e76a24">
                                    <animate attributeName="cx" repeatCount="indefinite" dur="1s" values="95;35" keyTimes="0;1" begin="0s"></animate>
                                    <animate attributeName="fill-opacity" repeatCount="indefinite" dur="1s" values="0;1;1" keyTimes="0;0.2;1" begin="0s"></animate>
                                </circle>
                                </g><g transform="translate(-15 0)">
                                <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#1c4595" transform="rotate(90 50 50)"></path>
                                <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#1c4595">
                                    <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;45 50 50;0 50 50" keyTimes="0;0.5;1"></animateTransform>
                                </path>
                                <path d="M50 50L20 50A30 30 0 0 1 80 50Z" fill="#1c4595">
                                    <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;-45 50 50;0 50 50" keyTimes="0;0.5;1"></animateTransform>
                                </path>
                                </g>
                                <!-- [ldio] generated by https://loading.io/ --></svg>
                                 </template>
                            </button>
                                </div>
                            </div>



                        </form>

                </div>
            </div>
    </div>
</template>

<script>
export default {
    data(){
        return{

            //form data yang akan dikirim
            form:{
                kriteria_id:'',
                bobot:'',
                nama:'',
            },
            // successMessage:'',
            loading:false,
            subjects:[],
            theErrors:[]
        };
    },
    mounted(){
                this.form.kriteria_id=this.$route.params.id;
        console.log(this.form.kriteria_id);
        this.getdatas();
    },
    methods:{
        async getdatas(){
            let response = await axios.get('/api/mahasiswa')
            // console.log(response.data);
            if(response.status === 200){
                this.subjects=response.data
            }
        },
        async store(){
            this.loading=true;
        try{
            let response = await axios.post(`/api/kriteriadetail/store`, this.form)
            if(response.status==200){
                // console.log(response.data);
                this.form.nama=""
                this.form.bobot=""
                this.loading=false
                this.theErrors=[]
                // this.successMessage=response.data.message
                // this.$toasted.show(response.data.message)
                let toast = this.$toasted.show(response.data.message, {
                    type:'success',
                    theme: "bubble",
                    position: "top-right",
                    duration : 5000
                });

            this.$router.push(`/kriteriadetail/${this.$route.params.id}/show`)
            }
            // console.log(response.data.message);
        }catch(e){

            this.loading=false
            this.theErrors=e.response.data.errors;
               let toast = this.$toasted.show("Terjadi kesalahan!", {
                    type:'error',
                    theme: "bubble",
                    position: "top-right",
                    duration : 5000
                });
        }
        }
    }


}
</script>

<style>

</style>
